import org.jetbrains.kotlin.gradle.dsl.KotlinVersion

plugins {
    id("buildsrc.convention.kotlin-jvm")
    id("buildsrc.convention.publish")
    `java-gradle-plugin`
}

kotlin {
    compilerOptions {
        // This plugin is loaded by the consumer's Gradle, whose embedded Kotlin (and KGP's
        // metadata reader) may be older than the Kotlin this project is built with. Pin the
        // metadata floor so older consumers can still load the plugin classes.
        // (Kotlin reads metadata one version ahead, so 2.1 still loads on Kotlin 2.0 / Gradle 8.x.)
        apiVersion.set(KotlinVersion.KOTLIN_2_1)
        languageVersion.set(KotlinVersion.KOTLIN_2_1)
    }
}

// ---------------------------------------------------------------------------
// BuildConfig: embed coordinates / plugin id / supported Kotlin range from gradle.properties
// (SSoT) so the plugin never hard-codes a version that drifts from the published artifacts.
// Registering the task provider as a srcDir wires the task dependency for every consumer of
// the source set (compileKotlin, sourcesJar, ...).
// ---------------------------------------------------------------------------
val generateBuildConfig = tasks.register("generateBuildConfig") {
    val values = mapOf(
        "GROUP_ID" to project.group.toString(),
        "VERSION" to project.version.toString(),
        "COMPILER_PLUGIN_ID" to providers.gradleProperty("COMPILER_PLUGIN_ID").get(),
        "SUPPORTED_KOTLIN_MIN" to providers.gradleProperty("SUPPORTED_KOTLIN_MIN").get(),
        "SUPPORTED_KOTLIN_MAX_TESTED_EXCLUSIVE" to
            providers.gradleProperty("SUPPORTED_KOTLIN_MAX_TESTED_EXCLUSIVE").get(),
    )
    val outputDir = layout.buildDirectory.dir("generated/buildConfig/kotlin")
    inputs.properties(values)
    outputs.dir(outputDir)
    val packageName = "com.example.compilerpluginsetup.gradle"
    doLast {
        val file = outputDir.get().file("${packageName.replace('.', '/')}/BuildConfig.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            buildString {
                appendLine("// Generated by :gradle-plugin:generateBuildConfig. Do not edit.")
                appendLine("package $packageName")
                appendLine()
                appendLine("internal object BuildConfig {")
                values.forEach { (key, value) -> appendLine("    const val $key: String = \"$value\"") }
                appendLine("}")
            },
        )
    }
}
kotlin.sourceSets.named("main") { kotlin.srcDir(generateBuildConfig) }

dependencies {
    compileOnly(libs.kotlinGradlePlugin)

    // ProjectBuilder sanity tests (fast). The real-build E2E lives in
    // :integration-test:test-gradle-plugin (Gradle TestKit).
    testImplementation(libs.kotlinGradlePlugin)
    testImplementation(libs.kotestRunnerJunit5)
    testImplementation(libs.kotestAssertionsCore)
}

gradlePlugin {
    plugins {
        create("examplePlugin") {
            id = providers.gradleProperty("COMPILER_PLUGIN_ID").get()
            displayName = "example-plugin Gradle plugin"
            description = "Applies the example-plugin Kotlin compiler plugin"
            implementationClass = "com.example.compilerpluginsetup.gradle.ExampleGradlePlugin"
        }
    }
}

// java-gradle-plugin + vanniktech also publishes the plugin marker
// (`<plugin-id>:<plugin-id>.gradle.plugin`) to Maven Central.
mavenPublishing {
    pom {
        name.set("example-plugin Gradle plugin")
        description.set("Gradle plugin that applies the example-plugin Kotlin compiler plugin")
    }
}
